AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pushes logs and metrics from AWS to Datadog.
Resources:
  loglambdaddfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Pushes logs and metrics from AWS to Datadog.
      Handler: lambda_function.lambda_handler
      MemorySize: 1024
      Runtime: python3.8
      Timeout: 120
      Layers:
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Python38:11'
        - !Sub 'arn:aws:lambda:${AWS::Region}:464622532012:layer:Datadog-Trace-Forwarder-Python38:3'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'cloudfront:GetDistributionConfig'
                - 'cloudfront:ListDistributions'
                - 'elasticloadbalancing:DescribeLoadBalancers'
                - 'elasticloadbalancing:DescribeLoadBalancerAttributes'
                - 'lambda:AddPermission'
                - 'lambda:GetPolicy'
                - 'lambda:RemovePermission'
                - 'redshift:DescribeClusters'
                - 'redshift:DescribeLoggingStatus'
                - 's3:GetBucketLogging'
                - 's3:GetBucketLocation'
                - 's3:GetBucketNotification'
                - 's3:ListAllMyBuckets'
                - 's3:PutBucketNotification'
                - 'logs:PutSubscriptionFilter'
                - 'logs:DeleteSubscriptionFilter'
                - 'logs:DescribeSubscriptionFilters'
              Resource: '*'
        - AmazonS3ReadOnlyAccess
